name: "gRPC's protoc action"
description: "Setup your runner with protoc environment"
author: "Anes Belfodil"
inputs:
  protoc-version:
    description: "The protoc version to make available on the path"
    required: false
  enable-grpc:
    description: "Enable gRPC generator plugins"
    required: false
  grpc-version:
    description: "The gRPC plugins version to make available on the path"
    required: false
  enable-grpc-web:
    description: "Enable gRPC web generator plugin"
    required: false
  grpc-web-version:
    description: "The gRPC web plugin version to make available on the path"
    required: false
  enable-dart:
    description: "Enable protoc Dart generator plugin"
    required: false
  dart-version:
    description: "The Dart version to make available on the path (ignored if enable-dart isn't true)"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "zap"
  color: "blue"
